# Generated by Django 5.1.3 on 2024-11-14 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('industry', models.CharField(choices=[('FS', 'Financial Services'), ('COM', 'Commercial'), ('IND', 'Industrial')], max_length=3)),
                ('duration', models.IntegerField()),
                ('duration_unit', models.CharField(choices=[('D', 'Days'), ('M', 'Months')], default='D', max_length=1)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_period', models.CharField(choices=[('H', '/Hour'), ('D', '/Day'), ('M', '/Month')], default='D', max_length=1)),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('SEK', 'Swedish Krona')], default='EUR', max_length=3)),
                ('requirements', models.TextField(help_text="Separate requirements with '/'")),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sagacity_dashboard.assignment')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
