# Generated by Django 5.1.3 on 2024-11-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_assignment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='duration_unit',
            field=models.CharField(choices=[('D', 'Days'), ('M', 'Months')], default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='assignment',
            name='rate_period',
            field=models.CharField(choices=[('H', '/Hour'), ('D', '/Day'), ('M', '/Month')], default='D', max_length=1),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
